sudo: required

services:
  - docker

language: go

os:
  - linux

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

before_install:
  - go get ./...
  - go build cmd/smoove/smoove.go
  - cd lumpy && go get gopkg.in/check.v1 && go test && cd ..
  - docker pull brentp/smoove:dev

script:
  - docker run -v `pwd`:/work/ -it brentp/smoove:dev ./tests/functional-tests.sh
