sample_info: conf/sample_info.csv
project:
  name: preTest
########################################################################################################################
### software path
#wrapper:  "file:/home/pengjia/ProjectSnake/snake-wrappers/bio/"
#mainEnv:  "/home/pengjia/miniconda3/envs/PQsnake/bin/" #path of software
#qcEnv:  "/home/pengjia/miniconda3/envs/ngsqc/bin/" #path of software
#baminfo: conf/baminfo.csv

########################################################################################################################
### output path
path_data: "../../ngs_test_data/data3/"
path_log:  "../../ngs_test_data/logs2/"
path_bm: "../../ngs_test_data/benchmark2/"

########################################################################################################################
### pipeline
loadBamFormat: up # csv, up
bamsample: "conf/bamsample.csv"  # if loadBamFormat is csv, you need to provide var_bcftools.smk csv file of sample bam files.

pipe:
  ## raw_read_qc
  trim: passqc # fastp, trim, passqc

  ## align
  aligner: bwa  #bwa, bowtie, bowtie2
  markdup: bioMarkDup #"noneMarkDup|picardMarkDup|bioMarkDup"
  realign: reAlign #"reAlign|noneReAlign",
  bqsr: BQSR # noneBQSR, BQSR
  leftAlign: LeftAlign # noneLeftAlign, LeftAlign
  fixMate: FixMate # noneFixMate, FixMate

  ## small variants (SNP and Indel)
  snpindel:
    - HC
    - HC_Hard_filter
    - HC_VQSR
    - HC_Joint
    - HC_Jonit_Hard_filter
    - HC_Joint_VQSR
    - bcftools
    - pindel
    - varscan
    - freebayes
    - deepvariant


    #  snpindel:
    #    - HC    GATK HaplotypeCaller
    #    - samtools
    #    - pindel
    #    - varscan
    #    - freebayes
    #    - deepvariant



  ## large variants (SV and CNV)
  svcnv:
    - metasv
    - delly
    - lumpy
    - smoove
    - breakdancer
    #    - cnvnator
    - pindel
    - metasv
    - manta
    - cnvcaller
    - cnvkit

  ## annotation

########################################################################################################################
### reference genome and database
ref:
  name: "GRCh38"
  chrom_num: 25   # the first chrom_num of chrom will be analysised by gatk
  # Path to the reference genome, ideally as it is provided by the GATK bundle.
  #  genome: "/home/DATA/REFGENOMEDB/human/GRCh38_full_analysis_set_plus_decoy_hla/genome/GRCh38_full_analysis_set_plus_decoy_hla.fa"
  genome: "/home/DATA/REFGENOMEDB/human/GRCh38.d1.vd1/genome/GRCh38.d1.vd1.fa"
  dbsnp: "/home/DATA/REFGENOMEDB/human/GRCh38.d1.vd1/variantsDB/dbsnp_146.hg38.vcf.gz"
  1KGomni: "/home/DATA/REFGENOMEDB/human/GRCh38.d1.vd1/variantsDB/1000G_omni2.5.hg38.vcf.gz"
  1KGp1snp: "/home/DATA/REFGENOMEDB/human/GRCh38.d1.vd1/variantsDB/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  hapmap: "/home/DATA/REFGENOMEDB/human/GRCh38.d1.vd1/variantsDB/hapmap_3.3.hg38.vcf.gz"
  mills1KG: "/home/DATA/REFGENOMEDB/human/GRCh38.d1.vd1/variantsDB/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  axiomPoly: "/home/DATA/REFGENOMEDB/human/GRCh38.d1.vd1/variantsDB/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
  germMutuct: "/home/DATA/REFGENOMEDB/human/GRCh38.d1.vd1/Mutect2/af-only-gnomad.hg38.vcf.gz"

########################################################################################################################
### threads for cluster
threads:
  ########## raw_read_qc.smk #########
  loadrawData: 4  # pigz
  fastqc: 4
  fastp: 4
  passqc: 1
  fastqc2: 4
  multiqc: 1      #fixed

  ########## bwa_gatk.smk #########
  Bwa: 8
  MergeBam: 8
  MarkDupWithPicard: 1
  NoneMarkDup: 1
  MarkDupWithBiobambam: 4
  NoneRealign: 1
  GATKReAlignPre: 4
  GATKReAlign: 1
  BamIndex: 4
  NoneBQSR: 1
  GATKBQSRPre: 1
  GATKBQSR: 1
  NoneLeftALign: 1
  GATKLeftAlign: 1
  NoneFixMate: 1
  GATKFixMate: 1
  LoadHQbam: 1

  ########## var_gatk_HC.smk #########
  HC_CallVar: 4
  HC_GT: 4
  HC_MergeVCF: 4
  HC_CombineCalls: 4
  HC_GT_jointCall: 4
  HC_MergeVCF_jointCall: 4
  HC_JointCall_SelectSNV: 4
  HC_JointCall_SelectIndel: 4
  HC_JointCall_FileterSNVHard: 4
  HC_JointCall_FileterINDElHard: 4
  HC_SelectSNV: 4
  HC_SelectIndel: 4
  HC_FileterSNVHard: 4
  HC_FileterINDElHard: 4
  HC_Joint_MakeSitesOnlyVcf: 4
  HC_Joint_VQSLOD: 4
  HC_Joint_applyVQSR: 4
  HC_VQSLOD: 4
  HC_applyVQSR: 4

  ########## var_freebayes.smk #########
  FB_CallVar: 4
  FB_Filter: 4
  ########## var_varscan.smk ##########
  Samtools_Mpileup: 2
  Varscan_Call: 2
  Varscan_Filter: 2
  Varscan_Call_SNV: 2
  Varscan_Filter_SNV: 2
  Varscan_Call_INDEL: 2
  Varscan_Filter_INDEL: 2


  ########## var_bcftools.smk #########
  Bcftools_Mpileup: 2
  Bcftools_Call: 2
  Bcftools_Filter: 2

  ########## var_metasv.smk ###########
  MetaSV: 20
  ########## var_meta.smk ###########
  Manta: 4
  Manta_conf: 2
  ########## var_pindel.smk ###########

  ########## var_delly.smk ############
  Delly_Call: 2
  Delly_GT: 2
  Delly2Bcf2vcfgz: 2
  ########## var_lumpy.smk ############
  Lumpy_Get_Discordants: 2
  Lumpy_Get_SplitReads: 2
  Lumpyexpress: 2
  ########## var_smoove.smk ############
  Smoove: 5

  ########## var_cnvnator.smk ######
  CNVnator: 2
  ########## var_breakdancer.smk ######
  BreakDancer: 2
  BreakDancer_Conf: 2
  ########## var_breakdancer.smk ######
  CNVcaller_make_kmer: 2
  CNVcaller_make_dup_align: 2
  CNVcaller_make_dup: 2
  CNVcaler_IndexReference: 2
  ########## var_breakdancer.smk ######

  #####################






  #filtering:
  #  # Set to true in order to apply machine learning based recalibration of
  #  # quality scores instead of hard filtering.
  #  vqsr: false
  #  hard:
  #    # hard filtering as outlined in GATK docs
  #    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
  #    snvs:
  #      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
  #    indels:
  #      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"








  #processing:
  #  remove-duplicates: true
  # Uncomment and point to var_bcftools.smk bed file with, e.g., captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals.
  # restrict-regions: captured_regions.bed
  # If regions are restricted, uncomment this to enlarge them by the given value in order to include
  # flanking areas.
  # region-padding: 100


########################################################################################################################
### parameters
params:
  gatk:
    HaplotypeCaller: ""
    BaseRecalibrator: ""
    GenotypeGVCFs: ""
    VariantRecalibrator: ""
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  trimmomatic:
    pe:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - " LEADING:3 "
        - " TRAILING:3 "
        - " SLIDINGWINDOW:4:15 "
        - " MINLEN:36 "
    se:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - " LEADING:3 "
        - " TRAILING:3 "
        - " SLIDINGWINDOW:4:15 "
        - " MINLEN:36 "
